"""Initial migration

Revision ID: 2502a3f3b67c
Revises: 
Create Date: 2025-07-28 12:56:21.627295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2502a3f3b67c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address_hash'), 'login_attempts', ['ip_address_hash'], unique=False)
    op.create_index(op.f('ix_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timestamp', 'timeframe', name='uq_market_data')
    )
    op.create_index('idx_market_data_symbol_time', 'market_data', ['symbol_id', 'timestamp'], unique=False)
    op.create_index('idx_market_data_timeframe', 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol_id'), 'market_data', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_market_data_timeframe'), 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('quote_currency', sa.String(length=10), nullable=True),
    sa.Column('min_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('quantity_precision', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notification_settings', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_per_trade', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_backtested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_portfolio_symbol', 'positions', ['portfolio_id', 'symbol_id'], unique=False)
    op.create_index('idx_positions_status', 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('external_order_id', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_executed_at', 'trades', ['executed_at'], unique=False)
    op.create_index('idx_trades_portfolio_symbol', 'trades', ['portfolio_id', 'symbol_id'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_portfolio_id'), 'trades', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol_id'), 'trades', ['symbol_id'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('suggested_stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('suggested_take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('suggested_position_size', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_generated_at', 'trading_signals', ['generated_at'], unique=False)
    op.create_index('idx_signals_status', 'trading_signals', ['status'], unique=False)
    op.create_index('idx_signals_strategy_symbol', 'trading_signals', ['strategy_id', 'symbol_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_index(op.f('ix_trading_signals_strategy_id'), 'trading_signals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_symbol_id'), 'trading_signals', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_signals_symbol_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_strategy_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_index('idx_signals_strategy_symbol', table_name='trading_signals')
    op.drop_index('idx_signals_status', table_name='trading_signals')
    op.drop_index('idx_signals_generated_at', table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_trades_symbol_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_portfolio_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_portfolio_symbol', table_name='trades')
    op.drop_index('idx_trades_executed_at', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index('idx_positions_status', table_name='positions')
    op.drop_index('idx_positions_portfolio_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_timeframe'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol_id'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('idx_market_data_timeframe', table_name='market_data')
    op.drop_index('idx_market_data_symbol_time', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_timestamp'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address_hash'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
